### ISSUE TITLE
Add instrument link and change semantics so data-transfer link is consumption/result

### ISSUE THREAD

**Issue by vainolo** [vainolo/Object-Process-Programming#155]

**Comment by vainolo** [comment]
Changed model and generated code.
Unit tests are passing, system tests with the existing models are also working, with the previous semantics of consumption/result.
Next - add the ability to add new instrument links, and then change runtime semantics.

**Comment by dovdori** [comment]
Very good!

 

We forgot to talk about the grade in the summer course which was not carried out.

I must provide a grade within a month at most so here is my suggestion for me to be able to give you a grade:

By Oct. 30 send me a draft paper with working title

“Object-Process Programming: The New ISO 19450 Standard-Based  Visual Programming Language”

for journal-of-visual-languages-and-computing

 

http://www.elsevier.com/journals/journal-of-visual-languages-and-computing/1045-926X/guide-for-authors

 

or check SoSym (higher impact factor)

 

Any news on OPM for MS?

 

Hag Sameach

 

Dov

**Comment by vainolo** [comment]
We can now add instrument links to the model. Last change is the semantics of these links. An instrument link will take the same semantics as the existing data-transfer link, and cons/res link will now have semantics of copy and erase.

**Comment by dovdori** [comment]
Hi
I have reached agreement with Adam the boss of Shmuela to have her work for us as we discussed to prepare the OPCloud front end infrastructure.
He is trying to get her work for OPCloud all next week. If this happens I need as many of you to be in the first meeting.
I know Aviv and Yang are abroad. Let me know ASAP your availability next week.
Dov

From: Nadav Oved [mailto:nadavo@gmail.com]
Sent: Friday, August 19, 2016 10:15 PM
To: Dori Dov <dori@ie.technion.ac.il>; Oleg Zendel <olegzendel@gmail.com>
Subject: Re: Today's counseling

Hi Dov,

Firstly, we wanted to say we found the meeting with Shmuela pleasant,​ interesting​ and very enriching​.
Our thoughts on Shmuela's proposals:

- Regarding the course:
We ​couldn't​ ​agree more,​ that having an experienced web development professional is essential for a serious course in this field and would
​completely​ change the course for the better.
We also think​ the popularity of such a course among​ serious students in the faculty would ​definitely increase if it's built well (most projects involve some level of web development), and​ all​ would greatly benefit from someone who is experienced in the field like Shmuela.
Experience is a huge part of software development, and currently we feel that Yang is just not experienced enough to lead such a course, despite his true learning efforts, and that he could have a hard time teaching and guiding other students in it​​. We feel that most students in the faculty who would be interested in taking such a course, have a fairly good background in coding concepts and fundamentals of software engineering, and that Yang will have a hard time giving them added value.

- Regarding OPCloud development:
After learning a bit more about Angular2 from Shmuela, we are open to the idea of incorporating it into our project at this stage.
We feel that Shmuela could greatly assist us in exploring the Angular2 option and that it might be worth a shot.
We discussed a few possibilities of ​implementation with Shmuela, and we feel that we have two main options:
1. Continue with RappidJS for the entire diagramming and editing needs, and have other peripheral aspects of OPCloud utilize Angular2 (user management, file management, etc...)
This way we are not losing any progress we made so far, and utilize the benefits of Angular2 for all non-diagramming related functionality.
2. Using JointJS as the core diagramming library (for implementing the different shapes and links on a canvas) and implement all other features (including the actual diagram editor) in Angular2.
Essentially lose RappidJS (and some progress we made with it) and replacing it with Angular2.
This means we would have to start coding the diagram editor and its features (which we already have in RappidJS) from scratch in Angular2 but could re-use the code we have already written for implementing the different OPM style shapes and links.
This would result in a more customized and native Angular2 app than option 1, which could ultimately be better and easier to further develop and maintain, but would force a set-back for us now, since we would have to implement a lot of features that we already have today in RappidJS from scratch in Angular2.

Bottom line - ​we​ think that with the help and guidance of Shmuela we could give Angular2 a good run, maybe it would eventually prove to be better than RappidJS, we are willing to give it a shot.
We are comfortable with Shmuela's proposal of developing a full structural basis for OPCloud in Angular2 utilizing what we've done so far in JointJS (diagramming features - shapes, links, canvas), and us developing the desired features upon that.
This way we minimize the set-back and still utilize code, implementation and knowledge we have in JointJS for core diagramming features, and gain the structural benefits of Angular2.

Good luck at whirlpool and enjoy your stay.

Regards,
Nadav and Oleg

On Fri, Aug 19, 2016 at 8:49 PM Dori Dov <dori@ie.technion.ac.il<mailto:dori@ie.technion.ac.il>> wrote:
Hi

I think her proposal can advance OPCloud very fast and help you when you are back for the semester.

I need to know what you think, also how was the meeting with Shmuela.
Dov
From: Dori Dov
Sent: Wednesday, August 17, 2016 5:19 PM
To: Nadav Oved <nadavo@gmail.com<mailto:nadavo@gmail.com>>; Oleg Zendel <olegzendel@gmail.com<mailto:olegzendel@gmail.com>>

Subject: Fwd: Today's counseling

Hi
What do you think about the proposal of Shmuela, both the development and the course?
Dov



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
From: Shmuela Jacobs <shmuela@500tech.com<mailto:shmuela@500tech.com>>
Date: 17/08/2016 15:25 (GMT-05:00)
To: Dori Dov <dori@ie.technion.ac.il<mailto:dori@ie.technion.ac.il>>
Cc: Adam Klein <adam@500tech.com<mailto:adam@500tech.com>>
Subject: Today's counseling

Hi Dubi,

I had a great pleasure to meet the OPCloud team in person and give some guidance.

The participants: Nadav (till noon), Oleg, Yang

Here's a summary of what we did today:

  *   Problems with JointJS and RapidJS were raised. These libraries should be further investigated - maybe we can find solutions.
  *   We discussed various methods for combining the libraries within the project.
  *   I introduced Angular 2

     *   I showed a presentation about the basic concepts and architecture - you can see it here: https://speakerdeck.com/shmool/angular-afterhours-angular-2-beginners-workshop
     *   I showed the structure of a small, real Angular 2 project, and explained how it all connects.
     *   Oleg and Yang cloned the project, set it up and ran it, and started making changes to the code to explore Angular 2 features.
I understand it will be very difficult to have another session like this before the semester begins, and in any case the team members are too busy to work on the project until then (full time summer jobs, exams, vacations, etc.)

I suggest taking over the project until then. I can create the basis on which the team will implement and refine the desired features. The base project will include:

  *   Angular 2 framework
  *   components (with JointJS / RapidJS) - using what was implemented so far
  *   canvas on which basic OPM diagrams can be created - with the basic features (Objects, Processes, links, subprocesses, states, zoom-in)
  *   making sure additional features can be easily added (link types, Things' essence and affiliation, etc.)
  *   NodeJS server connected to DB
If you agree, we will check my availability for this.

A note about Yang and the Web Development course: Yang lacks basic development skills and knowledge. Until now, Yang has not written even one line of code. (HTML, which he learns now in Coursera is not considered code...) It reflected in the work we did today.

I'm afraid making him in charge of the course, or even just teaching it, will not result with a good outcome. First, even though I believe he is diligent, I don't think he can understand all the concepts in this short time. Second, the students will expect a teacher with experience in Web development, and will be highly disappointed.

I'll be very happy to help with the course. But preparing the course may consume a large amount of time. If it's something you'd like to consider, you should consult with Adam.

Looking forward for your thoughts on all this :)
Shmuela

--
Shmuela Jacobs
Front end developer
Tel. +972-54-5864-783
[http://blog.500tech.com/content/images/2014/10/Logo-with-slogan-3.png]

**Comment by dovdori** [comment]
I'll be back in Israel only after 9.9, not sure what is meant by next week.

**Comment by vainolo** [comment]
Again you are sending mails to GitHub 😐

Arieh




On Mon, Sep 5, 2016 at 10:23 PM +0300, "dovdori" <notifications@github.com> wrote:










I'll be back in Israel only after 9.9, not sure what is meant by next week.
